[package]
authors = ["Eden <rust@eden2.com>"]
edition = "2018"
name = "fold_impls"
publish = false
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = {version = "1", features = ["full"]}
