name: build_turbo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - run: npm install
        working-directory: 'frontend'

      - run: npm run svelte-check
        working-directory: 'frontend'

      - run: npm run build
        working-directory: 'frontend'

      - run: npm install
        working-directory: 'prosemirror_collab_server'

      - run: npm run build
        working-directory: 'prosemirror_collab_server'

      - run: npm install
        working-directory: 'electron'

      - run: npm run build-neon
        working-directory: 'electron'

      - run: npm run make
        working-directory: 'electron'
