name: build_turbo

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  CARGO_TERM_COLOR: always

jobs:

  checklinks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        id: lychee
        with:
          args: --verbose --no-progress --exclude=crates.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15, macos-11.0]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - run: npm install
        working-directory: 'frontend'

      - run: npm run svelte-check
        working-directory: 'frontend'

      - run: npm run build
        working-directory: 'frontend'

      - run: npm install
        working-directory: 'electron'

      - run: npm run build-neon
        working-directory: 'electron'

      - run: cargo test

      - run: npm run make
        working-directory: 'electron'
