name: publish_turbo

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
env:
  CARGO_TERM_COLOR: always

jobs:

  publish:
    name: publish ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, 'turbo@0')"

    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - run: npm install
        working-directory: 'frontend'

      - run: npm run svelte-check
        working-directory: 'frontend'

      - run: npm run build
        working-directory: 'frontend'

      - run: npm install
        working-directory: 'electron'

      - run: npm run build-neon-release
        working-directory: 'electron'

      - name: Add macOS certs
        run: chmod +x add-macos-cert.sh && ./add-macos-cert.sh > /dev/null
        working-directory: 'electron'
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - run: npm run publish
        working-directory: 'electron'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
